### ISSUE TITLE
doesn't build with PostgreSQL 9.4

### ISSUE THREAD

**Issue by petere** [dimitri/prefix#8]
Maybe this check can be downgraded to a warning:

```
prefix.c:63:2: error: #error "Unknown or unsupported postgresql version"
```

Otherwise it's hard to test newer versions.

Actually, I'd just remove it.  If a version is not supported, you'll presumably be told be a compiler error or  test failure.
